### ISSUE TITLE
Doesn't provide information for boto3 Resource objects

### ISSUE THREAD

**Issue by Varriount** [jeshan/botostubs#1]
The data generated by the botostubs library doesn't appear to include information on data types used by the `Resource` classes - created by `boto3.resource`.

**Comment by jeshan** [comment]
Correct. I don't know how to support the higher-level resources yet.

**Comment by jeshan** [comment]
@Varriount finally got to work on this! There's also support for waiters and paginators. Take a look and let me know: `pip install --upgrade botostubs`. Example available in the README
