### ISSUE TITLE
Type does not populate with autocomplete is there a list of ENUMS?

### ISSUE THREAD

**Issue by jmjava** [jeshan/botostubs#18]
is there a list of botostubs enum values?  I cannot find the correct ENUM for kafka.   Autocomplete on the type is not working.  I found S3 from example.

def s3_client():
    s3 = boto3.client("s3")  # type: botostubs.S3
    return s3  <-- THIS WORKS 

def msk_client():
    msk = boto3.client("kafka")  # type: botostubs.KAFKA
    return msk <-- THIS DOES NOT WORK

**Comment by jeshan** [comment]
>  type: botostubs.KAFKA

Try: `botostubs.Kafka`. Sorry it wasn't obvious!

> is there a list of botostubs enum values? 

Not explicitly but here are some ways to find out:
1. Your IDE should help:
![image](https://user-images.githubusercontent.com/1020565/107070259-86727680-67fc-11eb-8f6f-285650698f6a.png)

2. Open a python shell and start typing like this and press TAB:
![image](https://user-images.githubusercontent.com/1020565/107069788-e1f03480-67fb-11eb-83a7-444606788dd8.png)

3. The [boto3 docs page](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html)'s sidebar. The names on there should do the trick:
![image](https://user-images.githubusercontent.com/1020565/107069734-d13fbe80-67fb-11eb-9fb8-874523f41101.png)

Feel free to reopen if needed

**Comment by jmjava** [comment]
Thanks - that works!  . It was the Caps :)  Not sure why the autocomplete is not giving hints for type in VSCode for me.

**Comment by jeshan** [comment]
@jmjava See if this thread is of any help: https://github.com/jeshan/botostubs/issues/2#issuecomment-500642261
