### ISSUE TITLE
How do we contribute?

### ISSUE THREAD

**Issue by shadycuz** [jeshan/botostubs#19]
I would like to add resources like `VPC` etc.

**Comment by jeshan** [comment]
Thanks for your interest.

Normally, you'd create a VPC with something like:
```python
import botostubs
import boto3

client = boto3.resource('ec2')  # type: botostubs.EC2.Ec2Resource
vpc = client.Vpc('id')
```
and you should have completion as shown in the README:
![image](https://user-images.githubusercontent.com/1020565/109190250-580a0a80-77ae-11eb-9b49-29226b253e69.png)


This project is designed to be automatically updated with (and mapped to) new apis added to boto3.
As such, I'd consider other features to be out of scope. (I hardly ever touch this codebase)

Could you provide an example of what you'd like to accomplish?

**Comment by shadycuz** [comment]
@jeshan where possible I prefer to use resources.  

```python
ec2 = boto3.resource('ec2')
vpc = ec2.Vpc('vpc-01250c74f7a4d1236')
```

Best example I can do on my phone. It was easy to get completion for the ec2 service resource but I had trouble with typing the vpc variable.

Edit: I just noticed that your screen shot covers my example. Let me get back at you tomorrow with my actual code because I couldn't get it to work and I tried everything.

**Comment by jeshan** [comment]
OK, then let me know what you see (and your IDE).
Or maybe you haven't updated the package in a long while: `pip install --upgrade botostubs`

**Comment by shadycuz** [comment]
Hey, 

What I was expecting was `botostubs.EC2.SomeResource`, so I was trying `botostubs.EC2.VPC` but nothing was auto-completing.  I finally figure it out thanks to your example: `botostubs.EC2.Ec2Resource.Vpc`. Its a bit long but you can create a type alias from it =)

**Comment by jeshan** [comment]
> I was trying botostubs.EC2.VPC

I thought of that but that would conflict with a VPC client and a VPC resource. That's why I followed the current pattern when I added support for resources.

**Comment by shadycuz** [comment]
@jeshan probably not worth changing it. Thanks for the great package. It's a gamechanger to not have to boto3 docs up in another tab.
