### ISSUE TITLE
S3.Bucket(name).objects collection (and others?) not showing

### ISSUE THREAD

**Issue by TeaEarlGrey** [jeshan/botostubs#24]
Thanks again for this great package!

From: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#bucket we know these are the resource's available collections:
 
  [multipart_uploads](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.multipart_uploads)
  [object_versions](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.object_versions)
  [objects](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.objects)

I was hoping/expecting these to be listed...have I misunderstood the scope of this package?

![image](https://user-images.githubusercontent.com/99149119/155861265-01ba8abc-ad28-422c-9ed5-522a736e5b37.png)

**Comment by jeshan** [comment]
good catch. I'll see what I can do today/soon.

**Comment by jeshan** [comment]
@TeaEarlGray
I improved it a bit and what you reported should be fixed. I could add some more enhancements but I actually don't care about AWS anymore.

Upgrade to 0.15.x and give it a try please. It should be out within 4 hours as per regular schedule.

**Comment by TeaEarlGrey** [comment]
Thanks, I'll give it a go! Im still early in my cloud journey (better late than never) and botostubs is a godsend.

Out of curiosity what have you moved to instead of AWS / why have you stopped caring?

**Comment by jeshan** [comment]
> what have you moved to instead of AWS / why have you stopped caring

With AWS, you will soon learn to maintain your sanity! But personally, let me just say that I don't believe big tech companies have my interests at heart anymore. You will sooner/later learn what I mean by these.



> botostubs is a godsend

Exactly! Why should I have had to write it? Think about that.

You can close this issue once you're satisifed with the fix.
