### ISSUE TITLE
Setup documentation for PyCharm

### ISSUE THREAD

**Issue by ext4** [jeshan/botostubs#3]
First, thank you for your work on this package as the lack of type information in boto3 has been a huge annoyance, although I had a little difficulty getting it to work in PyCharm.

After installing the package from PyPI, neither type annotations or type comments were having any affect. It turns out however that PyCharm was not indexing the botostubs package because the `__init__.py` file was too large as explained when I opened it and an error message was shown: 

> File size exceeds configured limit, code insight features not available

I was able to increase this limit under _Help -> Edit Custom Properties_ by adding `idea.max.intellisense.filesize=999999` and restarting PyCharm, which made the type annotations work as expected.

Perhaps this should be added to the `README`?

**Comment by jeshan** [comment]
Thanks for letting me know! Last week, I introduced inline docs and this grew the file massively. I didn't realise that it would exceed the default limit. I'll fix this momentarily.
