### ISSUE TITLE
Reg. botostubs Resource autocomplete not working

### ISSUE THREAD

**Issue by sarjunwadkar** [jeshan/botostubs#5]
Hi Jeshan

Thanks for developing  botostubs. its very useful tool. Delighted to hear about your journey in making this tool. its very exciting. Installed botostubs on my ubuntu. Its working for client but not for Resource object

obj = boto3.resource('s3') # type : botostubs.ResourceS3

so hear if type .(dot) after obj its not showing the properties.

For Client API you are using type like below, is there any analogy? or where will i find which type to use ?
s3 = boto3.client('s3') # type: botostubs.S3

once again thanks for building the tool and showing how to use AWS services end to end.

Regards

swanand

**Comment by sarjunwadkar** [comment]
Resolved. I was using wrong type. Correct type is as below.

obj = boto3.resource('s3') # type: botostubs.S3.S3Resource

thanks.

**Comment by jeshan** [comment]
Glad you solved it.
Btw I had some examples in the readme.
