### ISSUE TITLE
what should be type value ? 

### ISSUE THREAD

**Issue by sarjunwadkar** [jeshan/botostubs#6]
Hi Jeshan

thanks for developing this tool. its very useful. 

I am new to aws and wants to do programming.But I am stuck here. when botostubs
is installed and checked it started working for the example you have shown.
s3 = boto3.client('s3')    # type: botostubs.S3
s3 properties are shown. no issue.

But when I exit from the vscode and come back again then all things disappear and auto complete doesn't work. This is consistently happening sometimes it works other don't. 

what I observed is that, If i import 'sys' or 'os' package and then used 'sys.path.append()' using 
autocomplete feature of vs code then invoked s3. autocomplete then it start displaying properties. But behavior is not consistent. its very frustrating.

now I also want to create object for dynamodb , I am using below command but its not showing the properties.
dynamo = boto3.client('dynamodb')    # type: botostubs.Dynamodb 
dynamo = boto3.client('dynamodb')    # type: botostubs.DYNAMODB 
so I don't know if problem is with type definition .
 # type: botostubs.Dynamodb 
 # type: botostubs.DYNAMODB 

I think 'type :' is very important here otherwise it won't show property. do you have complete list of types for each aws object? so that no guessing.

Also in your video, you have shown when you type # type : , you automatically gets "botostubs" and subsequent property, how to get that? Its not working on my end.

Your help is highly appreciated.

Regards

swanand

**Comment by jeshan** [comment]
Hello Swanand,
My experience with VS Code is limited.

> This is consistently happening sometimes it works other don't

Somebody raised an issue with it a while ago. Please take a look:
#2 

In particular, you may have some luck by disabling Jedi intellisense if you have it enabled:
https://github.com/jeshan/botostubs/issues/2#issuecomment-500642261

> But behavior is not consistent. its very frustrating.

I'm afraid that's an issue with VS Code that you need to raise on some forum. You can ask them how to get code completion on the pip packages that you install (i.e botostubs).

> I also want to create object for dynamodb

For DynamoDB, you'd type: `# type: botostubs.DynamoDB`

> do you have complete list of types for each aws object?

No but it's based on boto3 service names, you can check the available services on the left here:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html

e.g for ECS, `type: botostubs.ECS`, for Alexa for Business, `type: botostubs.AlexaForBusiness`

Patterns for other types follow the examples in the Features section of the README:
https://github.com/jeshan/botostubs#features

> you have shown when you type # type : , you automatically gets "botostubs" and subsequent property, how to get that?

What you're seeing is me typing on JetBrains Intellij IDEA / PyCharm. You can try free PyCharm Community edition https://www.jetbrains.com/pycharm/


botostubs is IDE-independent and assumes you have code completion that works well in your favourite IDE.

**Comment by jeshan** [comment]
Hello Swanand,
My experience with VS Code is limited.

> This is consistently happening sometimes it works other don't

Somebody raised an issue with it a while ago. Please take a look:
#2 

In particular, you may have some luck by disabling Jedi intellisense if you have it enabled:
https://github.com/jeshan/botostubs/issues/2#issuecomment-500642261

> But behavior is not consistent. its very frustrating.
I'm afraid that's an issue with VS Code that you need to raise on some forum. You can ask them how to get code completion on the pip packages that you install (i.e botostubs).

> I also want to create object for dynamodb
For DynamoDB, you'd type: `# type: botostubs.DynamoDB`

> do you have complete list of types for each aws object?
No but it's based on boto3 service names, you can check the available services on the left here:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html

e.g for ECS, `type: botostubs.ECS`, for Alexa for Business, `type: botostubs.AlexaForBusiness`

Patterns for other types follow the examples in the Features section of the README:
https://github.com/jeshan/botostubs#features

> you have shown when you type # type : , you automatically gets "botostubs" and subsequent property, how to get that?
What you're seeing is me typing on JetBrains Intellij IDEA / PyCharm. You can try free PyCharm Community edition https://www.jetbrains.com/pycharm/


botostubs is IDE-independent and assumes you have code completion that works well in your favourite IDE.

**Comment by sarjunwadkar** [comment]
Hi Jeshan
Problem is resolved now. Disabled Jedi and enabled python search server. now it is consistently showing the auto complete. Thanks for detail response. much appreciated. please close the issue.

Regards
swanand
    On Thursday, 5 March, 2020, 02:58:49 pm IST, Jeshan Giovanni BABOOA <notifications@github.com> wrote:  
 
 
Closed #6.
